config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "events#index"
  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [ :new, :create, :destroy ]

  resources :users
  get "signup" => "users#new"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="relative max-w-4xl px-4 py-3 mx-auto mb-4 text-green-700 bg-green-100 border border-green-400 rounded" role="alert">
    <span class="block sm:inline"><%= flash[:notice] %></span>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="relative max-w-4xl px-4 py-3 mx-auto mb-4 text-red-700 bg-red-100 border border-red-400 rounded" role="alert">
    <span class="block sm:inline"><%= flash[:alert] %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-zinc-800">
  <p class="p-8 text-center text-white">Made in <span class="text-blue-500">Alex's Sweatshop</span></p>
</footer>

app/views/layouts/_header.html.erb
<header class="p-4 mb-10 bg-blue-500 shadow-md">
  <nav class="container flex items-center justify-between mx-auto">
    <%= link_to root_path, class: "flex items-center" do %>
      <%= image_tag "logo.png", class: "h-8 w-auto", alt: "Logo" %>
    <% end %>
    <ul class="flex items-center gap-8 text-gray-200 text-md">
      <li class="transition-all duration-200 hover:border-b-2 hover:border-white">
        <%= link_to 'All Events', events_path, class: "py-2" %>
      </li>
    </ul>
    <ul class="flex items-center gap-4">
      <% if current_user %>
        <li class="text-white">
          <%= link_to current_user.name, current_user %>
        </li>
        <li class="px-2 py-1 text-white border rounded-md">
          <%= link_to "Sign Out", session_path, data: { turbo_method: :delete } %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign In', new_session_path, class: "px-4 py-2 bg-white text-blue-500 rounded-lg hover:bg-gray-100 transition-colors duration-200" %>
        </li>
        <li>
          <%= link_to 'Sign Up', signup_path, class: "px-4 py-2 bg-white text-blue-500 rounded-lg hover:bg-gray-100 transition-colors duration-200" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Eventz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col min-h-screen">
    <%= render "layouts/header" %>
    <main class="flex-grow w-auto mx-auto">
      <%= render "layouts/flash" %>
      <%= yield %></main>
    <%= render "layouts/footer" %>
  </body>
</html>